bloggingsystem/bloggingsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('main/', include('mainapp.urls')),
    path('user/', include('userapp.urls')),
]

bloggingsystem/mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='mainapp'
urlpatterns = [
    path('blogpost/', views.blogpost, name='blogpost'),
    path('add_blog_details/',views.add_blog_details,name='add_blog_details'),
    path('view/',views.view_blog_details,name='view_blog_details'),
    path('edit/<int:blog_id>',views.edit_blog_details,name='edit_blog_details'),
    path('delete/<int:blog_id>',views.delete_blog_details,name='delete_blog_details'),
    path('comment_list/', views.comment_list, name='comment_list'),
]

bloggingsystem/userapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'userapp'
urlpatterns = [
    path('viewblogs', views.viewblogs, name='viewblogs'),
    path('blog_details_list', views.blog_details_list, name='blog_details_list'),
    path('submit_form/',views.submit_form,name='submit_form'),
    path('adduserprofile/',views.adduserprofile,name='adduserprofile'),
    path('open_blog/<int:blog_id>/',views.open_blog,name='open_blog'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloggingsystem/templates/navbar/mainnavbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog Zen</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #0FDFBC">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">Blog Zen</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'mainhomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Steps</a>
        </li>
          <a class="nav-link" href="{% url 'mainapp:blogpost' %}">Post Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mainapp:view_blog_details' %}">View Blogs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mainapp:comment_list' %}">View Comments</a>
        </li>
        <li class="nav-item">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
              <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">User</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Blogger</a>
          </li>
        </ul>
      <ul class = "navbar-nav ms-auto">
        <li>
          {% if user.is_authenticated %}
          <li class="nav-item">
        <span class="nav-link">Welcome, {{user.username}}</span>
        </li>
        <li class="nav-item">
          <a class="nav-item" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-item" href="{% url 'signup' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-item ms-2 " href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

        </li>
      </ul>

    </div>
  </div>
</nav>
{% block body%}

{% endblock %}
</body>
</html>

bloggingsystem/templates/navbar/projectnavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog Zen</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #62DAFE ">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">Blog Zen</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
              <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">User</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Blogger</a>
          </li>
        </ul>
      <ul class = "navbar-nav ms-auto">
        <li>
          {% if user.is_authenticated %}
          <li class="nav-item">
        <span class="nav-link">Welcome, {{user.username}}</span>
        </li>
        <li class="nav-item">
          <a class="nav-item" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-item" href="{% url 'signup' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-item ms-2 " href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

        </li>
      </ul>

    </div>
  </div>
</nav>
{% block body%}

{% endblock %}
</body>
</html>

bloggingsystem/templates/navbar/usernavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog Zen</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #0FDFBC">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">Blog Zen</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'userhomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'userapp:adduserprofile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'userapp:blog_details_list' %}">View Blogs</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
              <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">User</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Blogger</a>
          </li>
        </ul>
    </div>
  </div>
</nav>
{% block body%}

{% endblock %}
</body>
</html>