bloggingsystem/bloggingsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('main/', include('mainapp.urls')),
    path('user/', include('userapp.urls')),
]

bloggingsystem/mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='mainapp'
urlpatterns = [
    path('blogpost/', views.blogpost, name='blogpost'),
    path('add_blog_details/',views.add_blog_details,name='add_blog_details'),
    path('view/',views.view_blog_details,name='view_blog_details'),
    path('edit/<int:blog_id>',views.edit_blog_details,name='edit_blog_details'),
    path('delete/<int:blog_id>',views.delete_blog_details,name='delete_blog_details'),
    path('comment_list/', views.comment_list, name='comment_list'),
]

bloggingsystem/mainapp/models.py
from django.db import models

# Create your models here.
class BlogDetails(models.Model):
    blogtitle = models.CharField(max_length=255, **{'null': True, 'blank': True})
    BLOG_TYPES = [
        ('foodblogs', 'Food-blogs'),
        ('travelblogs', 'Travel-blogs'),
        ('petsblogs', 'Pets-blogs'),
    ]
    blogtype = models.CharField(max_length=20, choices=BLOG_TYPES, default='foodblogs')
    description = models.TextField(**{'null': True, 'blank': True})
    location = models.CharField(max_length=100, **{'null': True, 'blank': True})
    bloggerdetails = models.CharField(max_length=200, **{'null': True, 'blank': True})

    class Meta:
        db_table="BlogDetails"

bloggingsystem/mainapp/views.py
from django.shortcuts import render, get_object_or_404, redirect

from mainapp.models import BlogDetails


# Create your views here.
def blogpost(request):
    return render(request, 'mainapp/blogpost.html')

def add_blog_details(request):
    if request.method == 'POST':
        blogtitle = request.POST.get('blogtitle')
        blogtype = request.POST.get('blogtype')
        description = request.POST.get('description')
        location = request.POST.get('location')
        bloggerdetails = request.POST.get('bloggerdetails')

        blog_details = BlogDetails.objects.create(
            blogtitle=blogtitle,
            blogtype=blogtype,
            description=description,
            location=location,
            bloggerdetails=bloggerdetails,
        )
        blog_details.save()
        return render(request, 'mainapp/datainserted.html')
    return render(request, 'mainhomepage.html')

def view_blog_details(request):
    blog_details_list = BlogDetails.objects.all()
    return render(request, 'mainapp/view_blog_details.html',{'blog_details_list':blog_details_list})

def edit_blog_details(request, blog_id):
    blog_details = get_object_or_404(BlogDetails, id=blog_id)
    if request.method == 'POST':
        blog_details.blogtitle = request.POST.get('blogtitle')
        blog_details.blogtype = request.POST.get('blogtype')
        blog_details.description = request.POST.get('description')
        blog_details.location = request.POST.get('location')
        blog_details.bloggerdetails = request.POST.get('bloggerdetails')
        blog_details.save()
        return redirect('mainapp:view_blog_details')
    return render(request, 'mainapp/edit_blog_details.html',{'blog_details':blog_details})

def delete_blog_details(request, blog_id):
    blog_details = get_object_or_404(BlogDetails, id=blog_id)
    if request.method == 'POST':
        blog_details.delete()
        return redirect('mainapp:view_blog_details')
    return render(request, 'mainapp/edit_blog_details.html',{'blog_details':blog_details})

from userapp.models import OpenBlog
def comment_list(request):
    comment_list = OpenBlog.objects.all()
    return render(request, 'mainapp/comment_list.html', {'comment_list':comment_list})

bloggingsystem/templates/mainapp/blogpost.html
{% extends 'navbar/mainnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post Blog</title>
</head>
<body>
{% block body%}

<h1> Blog post page from Main app</h1>
<div>
    <div class = "container mt-5">
        <h3> Blog Post Form </h3>
        <form method="post" action="{% url 'mainapp:add_blog_details' %}">
        {% csrf_token %}
            <div class="form-group">
                <label for = "blogtitle">Blog Title</label>
                <input type = "text" class = "form-control" name = "blogtitle" id = "blogtitle" placeholder = "Enter the Blog Title">
            </div>
            <div class="form-group">
                <label for = "blogtype">Blog Type</label>
                <select class = "form-control" name = "blogtype" id = "blogtype">
                    <option value="select">Select Blog Type</option>
                    <option value="food">Food Blogs</option>
                    <option value="travel">Travel Blogs</option>
                    <option value="pets">Pets Blogs</option>
                </select>
                <div class = "form-group">
                    <label for = "description">Description</label>
                    <textarea class = "form-control" name = "description" id = "description" rows = "2" placeholder = "Enter the details"></textarea>
                </div>
                <div class="form-group">
                    <label for = "location">Location</label>
                    <input type = "text" class = "form-control" name = "location" id = "location" placeholder = "Enter the location">
                </div>
                <div class="form-group">
                    <label for = "bloggerdetails">Blogger Details</label>
                    <input type = "text" class = "form-control" name = "bloggerdetails" id = "bloggerdetails" placeholder = "Enter the Blogger Details">
                </div>
            </div>
            <br><br>
            <button type="submit" class="btn btn-primary">Post the blog</button>
        </form>
    </div>
</div>
{% endblock %}
</body>
</html>

bloggingsystem/templates/mainapp/comment_list.html
{% extends 'navbar/mainnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Comments</title>
</head>

<body>
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h5>Comments</h5>
            <table class="table" border="2">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Comment</th>
                    </tr>
                </thead>
                <tbody>
                    {% for comment in blog.comments.all %}
                    <tr>
                        <td>{{ comment.name }}</td>
                        <td>{{ comment.message }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2">No comments yet.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<style>
    table, th, td{
    border:2px solid black;
    }
</style>
{% endblock %}
</html>

bloggingsystem/templates/mainapp/datainserted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> Data Inserted </h1>
</body>
</html>

bloggingsystem/templates/mainapp/delete_blog_details.html
{% extends 'navbar/mainnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Blog</title>
</head>
<body>
{% block body%}
<div class="container mt-5">
    <div class="row justify-content-left">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <p>Are you sure you want to delete "{{blog_details.blogtitle }}"?</p>
                    <form method="post" action="{% url 'delete_blog_details' blog_details.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

bloggingsystem/templates/mainapp/edit_blog_details.html
{% extends 'navbar/mainnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>

{% block body%}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <form method="post" action="#">
                    {% csrf_token %}
                    <h1 align="center">Edit Blog</h1>
                    <div class="form-group">
                        <label for="blogtitle">Blog Title</label><br>
                        <input type="text" class="form-control" name="blogtitle" value="{{ blog_details.blogtitle}}" required><br>
                    </div>

                    <div class="form-group">
                        <label for="blogtype">Blog Type</label><br>
                        <select class="form-control" name="blogtype" required>
                            <option value="Food Blogs" {% if blog_details.blogtype == 'Food Blogs' %}selected{% endif %}> Food Blogs </option>
                            <option value="Travel Blogs" {% if blog_details.blogtype == 'Travel Blogs' %}selected{% endif %}> Travel Blogs </option>
                            <option value="Pets Blogs" {% if blog_details.blogtype == 'Pets Blogs' %}selected{% endif %}> Pets Blogs </option>
                        </select><br>
                    </div>

                    <div class="form-group">
                        <label for="description">Description</label><br>
                        <input type="text" class="form-control" name="description" value="{{ blog_details.description}}" required><br>
                    </div>

                    <div class="form-group">
                        <label for="location">Location</label><br>
                        <input type="text" class="form-control" name="location" value="{{ blog_details.location}}" required><br>
                    </div>

                    <div class="form-group">
                        <label for="bloggerdetails">Blogger Details</label><br>
                        <input type="text" class="form-control" name="bloggerdetails" value="{{ blog_details.bloggerdetails}}" required><br>
                    </div>

                    <div class="text-center"> <!-- Aligns the button to the center -->
                        <button type="submit" class="btn btn-primary">update</button>
                    </div><br>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}
</body>
</html>

bloggingsystem/templates/mainapp/view_blog_details.html
{% extends 'navbar/mainnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Blogs</title>
</head>
<body>
{% block body%}

<div class="container mt-5">
    <div class="row">
        {% for BlogDetails in blog_details_list %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ BlogDetails.blogtitle}}</h5>
                    <p class="card-text">Blog Type: {{ BlogDetails.get_blogtype_display }}</p>
                    <p class="card-text">Description: {{ BlogDetails.description }}</p>
                    <p class="card-text">Location: {{ BlogDetails.location }}</p>
                    <p class="card-text">Bloggerdetails: {{ BlogDetails.bloggerdetails }}</p>

                    <a href="{% url 'mainapp:edit_blog_details' BlogDetails.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'mainapp:delete_blog_details' BlogDetails.id %}" class="btn btn-primary">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}
</body>
</html>